# Generated by Django 4.2.4 on 2023-08-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansiedad',
            fields=[
                ('idansiedad', models.AutoField(primary_key=True, serialize=False)),
                ('dolordecabeza', models.IntegerField(blank=True, null=True)),
                ('ganasdecomer', models.IntegerField(blank=True, null=True)),
                ('cuestatrabajodormir', models.IntegerField(blank=True, null=True)),
                ('asustaconfacilidad', models.IntegerField(blank=True, null=True)),
                ('sufredetemblor', models.IntegerField(blank=True, null=True)),
                ('sesientenervioso', models.IntegerField(blank=True, null=True)),
                ('sufremaladigestion', models.IntegerField(blank=True, null=True)),
                ('dificlpensarconclaridad', models.IntegerField(blank=True, null=True)),
                ('sesientetriste', models.IntegerField(blank=True, null=True)),
                ('lloraconfrecuencia', models.IntegerField(blank=True, null=True)),
                ('tienedificultaddesuacdiarias', models.IntegerField(blank=True, null=True)),
                ('dificultadtomardesiciones', models.IntegerField(blank=True, null=True)),
                ('dificultadparahacertrabajo', models.IntegerField(blank=True, null=True)),
                ('dificildesempenarpapel', models.IntegerField(blank=True, null=True)),
                ('perdidointeresencosas', models.IntegerField(blank=True, null=True)),
                ('sientepersonainutil', models.IntegerField(blank=True, null=True)),
                ('hatenidoideadeacabarconsuvida', models.IntegerField(blank=True, null=True)),
                ('sesientecansado', models.IntegerField(blank=True, null=True)),
                ('tienesensacionesdesagradables', models.IntegerField(blank=True, null=True)),
                ('secansaconfacilidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ansiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datospersonales',
            fields=[
                ('iddatospersonales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=10, null=True)),
                ('estadocivil', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=20, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('gradoinstruccion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('anodeingreso', models.IntegerField(blank=True, null=True)),
                ('facultadoescuela', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('direccionactual', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('numerocel', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('vivecon', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('numerohermanos', models.IntegerField(blank=True, null=True)),
                ('familiarresponsable', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('numerocelresponsable', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('religion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'datospersonales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Psicosis',
            fields=[
                ('idpsicosis', models.AutoField(primary_key=True, serialize=False)),
                ('sientealherir', models.IntegerField(blank=True, null=True)),
                ('esunapersonaimportante', models.IntegerField(blank=True, null=True)),
                ('hanotadointerferencia', models.IntegerField(blank=True, null=True)),
                ('oyevoces', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'psicosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuarios', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=10, null=True)),
                ('password', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
